/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    DeleteModal: typeof import('./components/DeleteModal.vue')['default']
    IconAgilis: typeof import('./components/icons/IconAgilis.vue')['default']
    IconProject: typeof import('./components/icons/IconProject.vue')['default']
    InputDate: typeof import('./components/forms/InputDate.vue')['default']
    InputEmail: typeof import('./components/forms/InputEmail.vue')['default']
    InputPassword: typeof import('./components/forms/InputPassword.vue')['default']
    InputText: typeof import('./components/forms/InputText.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    LogoAgilis: typeof import('./components/icons/LogoAgilis.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    OrganizationNavbar: typeof import('./components/OrganizationNavbar.vue')['default']
    ProjectNavbar: typeof import('./components/ProjectNavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    Select: typeof import('./components/forms/Select.vue')['default']
    SettingsMenu: typeof import('./components/SettingsMenu.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TextArea: typeof import('./components/forms/TextArea.vue')['default']
  }
}
